### ISSUE TITLE
PCB Outline missing on panel

### ISSUE THREAD

**Issue by greenscreenflicker** [openscopeproject/InteractiveHtmlBom#196]
Hello,
i get the following issue when generating the bom. It's an PCB array.
It has edge outlines.
![grafik](https://user-images.githubusercontent.com/17407241/98930435-ee0a7580-24dc-11eb-8d45-58124b0aa851.png)

Best regards,
Michael

**Comment by greenscreenflicker** [comment]
Kicad version information
Application: Pcbnew

Version: (5.99.0-6849-g69c1171320), release build

Libraries:
	wxWidgets 3.0.5
	libcurl/7.71.0 OpenSSL/1.1.1g (Schannel) zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0

Platform: Windows 10 (build 10586), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Nov  6 2020 11:04:13
	wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8)
	Boost: 1.73.0
	OCE: 6.9.1
	Curl: 7.71.0
	ngspice: 32
	Compiler: GCC 10.2.0 with C++ ABI 1014

Build settings:
	KICAD_SCRIPTING=ON
	KICAD_SCRIPTING_MODULES=ON
	KICAD_SCRIPTING_PYTHON3=OFF
	KICAD_SCRIPTING_WXPYTHON=ON
	KICAD_SCRIPTING_WXPYTHON_PHOENIX=OFF
	KICAD_SCRIPTING_ACTION_MENU=ON
	KICAD_USE_OCE=ON
	KICAD_SPICE=ON

**Comment by greenscreenflicker** [comment]
Happens with empty pcb also
![grafik](https://user-images.githubusercontent.com/17407241/98931961-02e80880-24df-11eb-8012-af25d320fd1d.png)

**Comment by qu1ck** [comment]
This is fixed in latest revision, update your plugin from master.

**Comment by greenscreenflicker** [comment]
@qu1ck I used for testing the following commit. Please advice, if I missed an update.
![grafik](https://user-images.githubusercontent.com/17407241/99282233-b92b5500-2833-11eb-84f4-73578a1f6ef1.png)

**Comment by qu1ck** [comment]
No, that is the latest commit. 
You need to make sure that it was actually running, i.e. you don't have another older ibom folder in your plugins directory and you restarted kicad fully after updating the plugin.

**Comment by greenscreenflicker** [comment]
I confirmed that i am using the latest version. Error is still there.

**Comment by qu1ck** [comment]
I cannot reproduce your issue. I get this for an empty board on a recent nightly. You either don't have most recent nightly or most recent plugin.

![image](https://user-images.githubusercontent.com/3622532/99615862-08f35300-29d1-11eb-9516-33a0c8e90982.png)

The path in tortoisegit window suggests that you have the plugin checked out outside of kicad plugin directory. Make sure you have your links setup correctly or that you have copied the folder over recently. When updating the plugin by copying files always completely remove old plugin directory. If you have a filesystem symlink setup as described in installation instructions then simply doing a git checkout is fine.

Btw I just pushed another commit that fixes nightly compatibility. You need to update plugin to latest.
